### ISSUE TITLE
TypeError: Cannot read property 'suites' of undefined

### ISSUE THREAD

**Issue by JayeshRGujar** [Antontelesh/mochawesome-merge#20]
I am getting the below error while merging the mochawesome report.
**Command**
$ npx mochawesome-merge — reportDir mochawesome-report > mochawesome-report/output.json

**ERROR:** Failed to merge reports

TypeError: Cannot read property 'suites' of undefined
    at report (C:\Users\admin\Documents\ipapps-cypress\node_modules\mochawesome-merge\lib\index.js:78:66)
    at Array.map (<anonymous>)
    at collection (C:\Users\admin\Documents\ipapps-cypress\node_modules\mochawesome-merge\lib\utils.js:3:44)
    at fns.reduce (C:\Users\admin\Documents\ipapps-cypress\node_modules\mochawesome-merge\lib\utils.js:1:121)
    at Array.reduce (<anonymous>)
    at value (C:\Users\admin\Documents\ipapps-cypress\node_modules\mochawesome-merge\lib\utils.js:1:101)
    at fns.reduce (C:\Users\admin\Documents\ipapps-cypress\node_modules\mochawesome-merge\lib\utils.js:1:121)
    at Array.reduce (<anonymous>)
    at value (C:\Users\admin\Documents\ipapps-cypress\node_modules\mochawesome-merge\lib\utils.js:1:101)

---------------
Dependencies and versions:
  "devDependencies": {
    "@cypress/snapshot": "^2.1.3",
    "cypress": "^3.3.1",
    "cypress-image-snapshot": "^3.0.2",
    "cypress-slack-reporter": "^0.3.1",
    "mocha": "^5.2.0",
    "mocha-junit-reporter": "^1.23.0",
    "mocha-multi-reporters": "^1.1.7",
    "mochawesome": "^4.0.0",
    "mochawesome-merge": "^1.0.7",
    "mochawesome-report-generator": "^4.0.0",
    "regenerator-runtime": "^0.13.2"
  }

**Comment by Antontelesh** [comment]
@JayeshRGujar mochawesome-merge@1 does not support mochawesome@4.
Please, update it to version 2

**Comment by JayeshRGujar** [comment]
@Antontelesh Thanks It worked
