### ISSUE TITLE
Error: Pattern matched no report files

### ISSUE THREAD

**Issue by arinanda** [Antontelesh/mochawesome-merge#36]
Hi, I try to merge my generated json report, but it always show `ERROR: Failed to merge reports`
```
Error: Pattern [./report/mochawesome/mochawesome*.json] matched no report files
    at pattern (/Users/ba-00004636/Documents/app/cypress/node_modules/mochawesome-merge/lib/index.js:14:11)
    at Array.map (<anonymous>)
    at items (/Users/ba-00004636/Documents/app/cypress/node_modules/mochawesome-merge/lib/utils.js:3:46)
    at merge (/Users/ba-00004636/Documents/app/cypress/node_modules/mochawesome-merge/lib/index.js:59:17)
    at Object.<anonymous> (/Users/ba-00004636/Documents/app/cypress/node_modules/mochawesome-merge/bin/mochawesome-merge.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tkpd-e2e@2.0.0 merge_reports: `mochawesome-merge ['./report/mochawesome/mochawesome*.json'] > report/mochawesome/output.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tkpd-e2e@2.0.0 merge_reports script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ba-00004636/.npm/_logs/2020-01-07T07_48_38_993Z-debug.log
The terminal process terminated with exit code: 1
```

version:
```
    "mocha": "^5.2.0",
    "mochawesome": "^4.0.1",
    "mochawesome-merge": "^4.0.0",
```

script:
```
"merge_reports": "mochawesome-merge ['./report/mochawesome/mochawesome*.json'] > report/mochawesome/output.json",
```

directory structure:
![image](https://user-images.githubusercontent.com/17931311/71878033-45bdaf00-315d-11ea-9b13-1890e664aac3.png)

please help🙏🏻

**Comment by Antontelesh** [comment]
@arinanda, you just need to remove brackets around your glob pattern. Square brackets in documentation mean only that this parameter is optional.

```
mochawesome-merge ./report/mochawesome/mochawesome*.json > report/mochawesome/output.json
```

**Comment by arinanda** [comment]
@Antontelesh ah, my bad hahaha I think those square brackets are required. It works now and thankyou for your quick response 👍🏻
