### ISSUE TITLE
Getting error TypeError: items.map is not a function

### ISSUE THREAD

**Issue by reidharry** [Antontelesh/mochawesome-merge#45]
@Antontelesh 

We've followed the steps mentioned in this URL https://medium.com/cypress-io-thailand/generate-a-beautiful-test-report-from-running-tests-on-cypress-io-371c00d7865a to generate report using mochawesome-merge.

Also we've changed `reportDir` to `files` as mentioned in V4.

```
const reporterOptions = {
    files: './' + results.config.reporterOptions.reportDir + '/*.json',
}
```

Getting error as
```
node:55052) UnhandledPromiseRejectionWarning: TypeError: items.map is not a function
    at /usr/local/var/www/client/node_modules/mochawesome-merge/lib/utils.js:3:46
    at merge (/usr/local/var/www/client/node_modules/mochawesome-merge/lib/index.js:59:17)
    at generateReport (/usr/local/var/www/client/cypress_runner.js:52:12)
    at /usr/local/var/www/client/cypress_runner.js:45:5
    at tryCatcher (/usr/local/var/www/client/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/local/var/www/client/node_modules/bluebird/js/release/promise.js:673:18)
```

**Comment by Antontelesh** [comment]
Hey @reidharry, could you check what your reports are looking like before supplied to mochawesome-merge? Also, what your `files` property expression evaluates to?

**Comment by Antontelesh** [comment]
Also, could you try wrapping your `files` value with an array, like this?

```js

const reporterOptions = {
    files: ['./' + results.config.reporterOptions.reportDir + '/*.json'],
}
```

**Comment by reidharry** [comment]
@Antontelesh 

files value `./cypress/report/mochawesome-report/*.json`

Please refer the report file, i've renamed `json` to `txt` while upload here because GitHub not allowing to upload json file.

[mochawesome_05112020_114212.txt](https://github.com/Antontelesh/mochawesome-merge/files/4608015/mochawesome_05112020_114212.txt)

[mochawesome_05112020_114653.txt](https://github.com/Antontelesh/mochawesome-merge/files/4608016/mochawesome_05112020_114653.txt)

**Comment by reidharry** [comment]
> Also, could you try wrapping your `files` value with an array, like this?
> 
> ```js
> const reporterOptions = {
>     files: ['./' + results.config.reporterOptions.reportDir + '/*.json'],
> }
> ```

Sure. Will check and let you know.

**Comment by reidharry** [comment]
@Antontelesh Thank you. It's working fine.

**Comment by Antontelesh** [comment]
@reidharry great! Was glad to help you
